spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://10.129.0.198:3306/ApolloPortalDB?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: D:/logs/apollo/apollo-adminservice.log


