spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://10.129.0.198:3306/ApolloConfigDB?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

ctrip:
  appid: 100003171
  
server:
  port: 8080
  
logging:
  file: /opt/logs/100003171/apollo-configservice.log
